/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

/**
 *
 * @author Žofia
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Žofia
 */
public class Referent_ovladanie extends javax.swing.JFrame {

Connection con = javaconnect.connectdb();
PreparedStatement ps = null;
ResultSet rs = null;

    /**
     * Creates new form Referent_ovladanie
     */
    public Referent_ovladanie() {
        initComponents();
    }

    /**
     *
     * @param IDOFR from class Referent 
     */
    public Referent_ovladanie(String IDOFR){
        initComponents();
        jLabel1.setText(IDOFR); //display ID into jLabel 
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableREF = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 510));
        getContentPane().setLayout(null);

        tableREF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableREF);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(330, 0, 369, 360);

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel11.setText("Logged referent (ID) :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 20, 260, 40);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        jLabel1.setText("X");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 30, 40, 20);

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/programovanie_button/button_refresh (1).png"))); // NOI18N
        refresh.setContentAreaFilled(false);
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(400, 360, 240, 100);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/programovanie_button/button_student-finished (1).png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(-20, 20, 370, 180);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/programovanie_button/button_logout (2).png"))); // NOI18N
        Logout.setContentAreaFilled(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(0, 370, 200, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/9992992C-6635-4AA4-9DA0-313EF9BC21D7.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 840, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
     String labelText = jLabel1.getText(); //save text from jLable into variable 
     /*
     Select everything from certain table by ID of referent and order by Monday-Friday and time from lowest to highest 
     Days of week are Strings so it take first letters from A to Z and by CASE we use 1 insted of Monday and order by 1 to 5 
     */
     String table = "SELECT * FROM APP.REF"+labelText+" ORDER BY CASE WHEN DAY = 'Monday' THEN 1 WHEN DAY = 'Tuesday' THEN 2 WHEN DAY = 'Wednesday' THEN 3 WHEN DAY = 'Thursday' THEN 4 WHEN DAY = 'Friday' THEN 5 END ASC, TIME ASC " ;
     System.out.println(table);
        try {
            ps = con.prepareStatement(table);
            rs = ps.executeQuery();
            DefaultTableModel tablemodel = new DefaultTableModel(new String[]{"NAME", "SURNAME", "PHONE", "TIME", "DAY"}, 0); //create table in window 
            while (rs.next()) { //saving information from table from database to table in window 
                String NAME = rs.getString("NAME");
                String SURNAME = rs.getString("SURNAME");
                String PHONE = rs.getString("PHONE");
                String TIME = rs.getString("TIME");
                String DAY = rs.getString("DAY");
                tablemodel.addRow(new Object[]{NAME, SURNAME, PHONE, TIME, DAY});
            }
            tableREF.setModel(tablemodel);
            ps.close();
            rs.close();
        } catch (Exception e) {
            System.out.println("" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    /*
    DELETE row from table when student is equipped 
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String labelText = jLabel1.getText();
       int ROW_STUDENT = tableREF.getSelectedRow();
       String DATA_CELL = tableREF.getModel().getValueAt(ROW_STUDENT, 2).toString(); //get PHONE number of student 
       String a=DATA_CELL;
       int num = Integer.parseInt( a ); //convert PHONE to integer 
       String tableSTUDENT = "DELETE FROM APP.REF"+labelText+" where PHONE="+num ; 
       try {
        ps = con.prepareStatement(tableSTUDENT);
        ps.executeUpdate();
    } catch (SQLException ex) {
        Logger.getLogger(Referent_ovladanie.class.getName()).log(Level.SEVERE, null, ex);
    }
       refreshActionPerformed(evt); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        dispose();
        new Choice().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Referent_ovladanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Referent_ovladanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Referent_ovladanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Referent_ovladanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Referent_ovladanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tableREF;
    // End of variables declaration//GEN-END:variables

}

