/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

/**
 *
 * @author Žofia
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Žofia
 */
public class Referent_ovladanie extends javax.swing.JFrame {

Connection con = javaconnect.connectdb();
PreparedStatement ps = null;
ResultSet rs = null;

    /**
     * Creates new form Referent_ovladanie
     */
    public Referent_ovladanie() {
        initComponents();
    }

    /**
     *
     * @param IDOFR from class Referent 
     */
    public Referent_ovladanie(String IDOFR){
        initComponents();
        jLabel1.setText(IDOFR); //display ID into jLabel 
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableREF = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableREF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableREF);

        jLabel11.setText("Logged referent (ID) :");

        jLabel1.setText("X");

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refresh)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh)
                    .addComponent(jButton2))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
     String labelText = jLabel1.getText(); //save text from jLable into variable 
     /*
     Select everything from certain table by ID of referent and order by Monday-Friday and time from lowest to highest 
     Days of week are Strings so it take first letters from A to Z and by CASE we use 1 insted of Monday and order by 1 to 5 
     */
     String table = "SELECT * FROM APP.REF"+labelText+" ORDER BY CASE WHEN DAY = 'Monday' THEN 1 WHEN DAY = 'Tuesday' THEN 2 WHEN DAY = 'Wednesday' THEN 3 WHEN DAY = 'Thursday' THEN 4 WHEN DAY = 'Friday' THEN 5 END ASC, TIME ASC " ;
     System.out.println(table);
        try {
            ps = con.prepareStatement(table);
            rs = ps.executeQuery();
            DefaultTableModel tablemodel = new DefaultTableModel(new String[]{"NAME", "SURNAME", "PHONE", "TIME", "DAY"}, 0); //create table in window 
            while (rs.next()) { //saving information from table from database to table in window 
                String NAME = rs.getString("NAME");
                String SURNAME = rs.getString("SURNAME");
                String PHONE = rs.getString("PHONE");
                String TIME = rs.getString("TIME");
                String DAY = rs.getString("DAY");
                tablemodel.addRow(new Object[]{NAME, SURNAME, PHONE, TIME, DAY});
            }
            tableREF.setModel(tablemodel);
            ps.close();
            rs.close();
        } catch (Exception e) {
            System.out.println("" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    /*
    DELETE row from table when student is equipped 
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String labelText = jLabel1.getText();
       int ROW_STUDENT = tableREF.getSelectedRow();
       String DATA_CELL = tableREF.getModel().getValueAt(ROW_STUDENT, 2).toString(); //get PHONE number of student 
       String a=DATA_CELL;
       int num = Integer.parseInt( a ); //convert PHONE to integer 
       String tableSTUDENT = "DELETE FROM APP.REF"+labelText+" where PHONE="+num ; 
       try {
        ps = con.prepareStatement(tableSTUDENT);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Student was successfully equipped");
    } catch (SQLException ex) {
        Logger.getLogger(Referent_ovladanie.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Referent_ovladanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Referent_ovladanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Referent_ovladanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Referent_ovladanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Referent_ovladanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tableREF;
    // End of variables declaration//GEN-END:variables

}

