/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

/**
 *
 * @author Žofia
 */

public class Referent extends javax.swing.JFrame {

Connection con = javaconnect.connectdb();
PreparedStatement ps = null;
ResultSet rs = null;
    /**
     * Creates new form Referent
     */
    public Referent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameR = new javax.swing.JTextField();
        passwordR = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ID_REF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 530));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        jLabel1.setText("REFERENT LOGIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 30, 480, 50);

        usernameR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameRActionPerformed(evt);
            }
        });
        jPanel1.add(usernameR);
        usernameR.setBounds(190, 132, 140, 30);
        jPanel1.add(passwordR);
        passwordR.setBounds(190, 182, 140, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 110, 160, 60);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 170, 79, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/programovanie_button/button_login (1).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 320, 210, 80);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 230, 70, 40);

        ID_REF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_REFActionPerformed(evt);
            }
        });
        jPanel1.add(ID_REF);
        ID_REF.setBounds(190, 232, 70, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/197829CB-4D36-4D01-88A7-F7841FF4911B.jpeg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 900, 480);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameRActionPerformed

    private void ID_REFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_REFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_REFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String loginR = " SELECT * FROM APP.ALLREFERENTS WHERE NAME=? AND PASSWORD=? AND ID_REF=?"; //check if the referent is in the table 
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        
        try {
            ps=con.prepareStatement(loginR); //connection to database 
            ps.setString(1, usernameR.getText()); //send userane from textfield to select 
            ps.setString(2, passwordR.getText()); //send password to select
            ps.setString(3, ID_REF.getText()); //send id to select
            
            rs=ps.executeQuery(); //use select with variables upper and save it to rs
            if(rs.next()){ //if select found something
                String insertR = "INSERT into APP.REGISTER_REF(TIME_REF,NAME_REF,ID_REF) values (?,?,?)"; //save referent login to table 
                ps=con.prepareStatement(insertR); 
                ps.setString(1, timestamp.toString());
                ps.setString(2, usernameR.getText());
                ps.setString(3, ID_REF.getText());
                String NameOFR= usernameR.getText();
                String IDOFR= ID_REF.getText();
                
                ps.executeUpdate();
                dispose();
                
                
                new Referent_ovladanie(IDOFR).setVisible(true); //open new window and send IDOFR to the new class 
            }else {
                JOptionPane.showMessageDialog(null,"Login fail!"); //if select did not find anything
            }
            
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Referent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Referent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Referent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Referent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Referent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_REF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordR;
    private javax.swing.JTextField usernameR;
    // End of variables declaration//GEN-END:variables
}
