/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Žofia
 * Student registration 
 */
public class Student extends javax.swing.JFrame {
    
Connection con = javaconnect.connectdb(); //calling method for connection
PreparedStatement ps = null; //send infromation from class to database 
ResultSet rs = null;  //sned infotrmation from database to class
String time;
String tablename;



    /**
     * Creates new form Student
     * 
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        grade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        regterm = new javax.swing.JLabel();
        timechoice = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        day = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 600));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 540));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        jLabel1.setText("STUDENT REGISTRATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 40, 660, 59);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(220, 120, 163, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(152, 155, 60, 30);

        grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Bc", "2.Bc", "3.Bc", " " }));
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });
        jPanel1.add(grade);
        grade.setBounds(220, 240, 70, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("Grade");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 240, 130, 25);

        Confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/programovanie_button/button_confirm (3).png"))); // NOI18N
        Confirm.setContentAreaFilled(false);
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(Confirm);
        Confirm.setBounds(240, 400, 250, 130);
        jPanel1.add(regterm);
        regterm.setBounds(539, 287, 152, 51);

        timechoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "13:00", "13:15", "13:30", "13:45", "14:00" }));
        timechoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timechoiceActionPerformed(evt);
            }
        });
        jPanel1.add(timechoice);
        timechoice.setBounds(220, 280, 80, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Time");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 280, 150, 25);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Phone number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 200, 140, 25);

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone);
        phone.setBounds(220, 200, 163, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setText("Surname");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 110, 100, 40);
        jPanel1.add(surname);
        surname.setBounds(220, 160, 163, 30);

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", " " }));
        jPanel1.add(day);
        day.setBounds(220, 320, 100, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setText("Day");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 320, 110, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/programovanie_button/button_cancel (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 420, 240, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programis/B59E1BAD-7CDA-4BBC-8B58-27A02B83CC0B.jpeg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 10, 700, 560);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-30, -10, 810, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeActionPerformed
     /*
    method for registrate students
    @param login returns SELECT 
    */
    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        
        /*
        save name from ComboBox into variable tablename and then work with certain table for every referent
        */
        if (grade.getSelectedItem()=="1.Bc")
        {
            tablename = " APP.REF1 ";
        }
        else if (grade.getSelectedItem()=="2.Bc")
        {
            tablename = " APP.REF2 " ;
        }
        else 
        {
            tablename = " APP.REF3 " ;
        }
        
        
        
        String name1= name.getText(); //get informatoin from text field and save it into variables
        String surname1= surname.getText();
        String phone1= phone.getText();
        if ((name1.equals(""))||(surname1.equals(""))||(phone1.equals(""))) //text field cannot be empty
     {
         JOptionPane.showMessageDialog(null,"missing information");
     }
     
     else{
    /*
            Look if PHONE number is already in the table.
            If number is in the table it means that student has already logged term 
            */
     String login = "SELECT TIME, DAY from " + tablename +  "WHERE PHONE=?"; //PHONE is uniqe number so we can use it as identifier 
     try {
        ps=con.prepareStatement(login); //connect to database and use command select..
        ps.setString(1, phone.getText()); //under ? save text from PhoneNumber text field
     
        rs= ps.executeQuery(); //look for result 
        if(rs.next()){ //rs is not null ...select found something
           String time = rs.getString("TIME"); 
           JOptionPane.showMessageDialog(null,"You´ve already had term at " +time);
           dispose();
    
         
        }
        /*
        Check if is time and day free
        */
        else {
            String find = "SELECT * from" + tablename + "WHERE TIME = '"+timechoice.getSelectedItem()+"' AND DAY = '"+day.getSelectedItem()+"' " ;
            ps=con.prepareStatement(find); //connection
            rs = ps.executeQuery(); //use command select... in the database
            if(rs.next()){ //if time and day is already in the table -> term is busy
                JOptionPane.showMessageDialog(null,"Sorry,your term is busy");         
            }
            /*
            If day and time is free then save the student info from GUI
            */
            else { 
                
                String insert = "INSERT into" + tablename + "(NAME, SURNAME, PHONE, TIME, DAY) values (?,?,?,?,?)";
                ps = con.prepareStatement(insert); 
                ps.setString(1, name.getText()); //save variables under ?
                ps.setString(2, surname.getText());
                ps.setString(3, phone.getText());
                ps.setString(4, timechoice.getSelectedItem().toString()); //convert object from ComboBox into String
                ps.setString(5, day.getSelectedItem().toString());
                ps.executeUpdate(); //update table 
                JOptionPane.showMessageDialog(null,"Successful registration \n Your term is at " +timechoice.getSelectedItem());
                dispose();
                String phone_number = phone.getText();
                new welcome().setVisible(true); //show window with information about Covid 
               
        }
        
            
            
        }
// TODO add your handling code here:
    } catch (SQLException ex){
    }

    }
    }//GEN-LAST:event_ConfirmActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void timechoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timechoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timechoiceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose(); 
    new Choice().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JComboBox<String> grade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel regterm;
    private javax.swing.JTextField surname;
    private javax.swing.JComboBox<String> timechoice;
    // End of variables declaration//GEN-END:variables
}
